resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: springai-chat-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
  - target:
      kind: Deployment
      name: springai-ui
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
