apiVersion: v1
kind: Service
metadata:
  name: springai-chat-service
  namespace: springai
spec:
  selector:
    app: springai-chat-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
