apiVersion: v1
kind: ConfigMap
metadata:
  name: springai-platform-config
  namespace: springai
data:
  SPRING_PROFILES_ACTIVE: local
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: springai
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  OLLAMA_BASE_URL: http://ollama:11434
