apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springai-platform-ingress
  namespace: springai
spec:
  ingressClassName: nginx
  rules:
    - host: springai.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: springai-ui
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: springai-chat-service
                port:
                  number: 8080
